"""Markdown report generator."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from code_audit.models.finding import Severity
from code_audit.models.report import AuditReport


def render_markdown_report(report: AuditReport) -> str:
    """Generate a markdown report from the audit results."""
    lines: list[str] = []

    # Header
    lines.append("# Code Audit Report")
    lines.append("")
    lines.append(f"**Audit ID**: `{report.audit_id}`")
    lines.append(f"**Date**: {report.timestamp.strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append(f"**Project**: `{report.target_path}`")
    lines.append(f"**Mode**: {report.mode}")
    lines.append(f"**Diff target**: `{report.diff_target}`")
    lines.append(f"**Duration**: {report.duration_seconds:.1f}s")
    lines.append(f"**Providers**: {', '.join(report.llm_providers_used)}")
    lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append("")
    s = report.summary
    if s.total_findings == 0:
        lines.append("No issues found. The code looks clean.")
    else:
        lines.append(f"| Metric | Count |")
        lines.append(f"|--------|-------|")
        lines.append(f"| Total findings | **{s.total_findings}** |")
        lines.append(f"| 🔴 Important | {s.important} |")
        lines.append(f"| 🟡 Nit | {s.nit} |")
        lines.append(f"| 🟣 Pre-existing | {s.pre_existing} |")
        lines.append(f"| Files reviewed | {s.files_reviewed} |")
    lines.append("")

    # Dimension breakdown
    if s.dimension_summaries:
        lines.append("### By Dimension")
        lines.append("")
        lines.append("| Dimension | Findings | Important | Nit | Pre-existing | Model | Duration |")
        lines.append("|-----------|----------|-----------|-----|-------------|-------|----------|")
        for ds in s.dimension_summaries:
            lines.append(
                f"| {ds.dimension} | {ds.total_findings} | {ds.important} | "
                f"{ds.nit} | {ds.pre_existing} | {ds.agent_model} | {ds.duration_seconds:.1f}s |"
            )
        lines.append("")

    if not report.findings:
        return "\n".join(lines)

    # Findings by severity
    findings_by_severity = report.findings_by_severity

    for severity in [Severity.IMPORTANT, Severity.NIT, Severity.PRE_EXISTING]:
        findings = findings_by_severity.get(severity, [])
        if not findings:
            continue

        lines.append(f"## {severity.emoji} {severity.label} ({len(findings)})")
        lines.append("")

        for finding in findings:
            lines.append(f"### {finding.title}")
            lines.append("")
            lines.append(f"**Location**: `{finding.location.display}`")
            lines.append(f"**Dimension**: {finding.dimension}")
            lines.append(f"**Confidence**: {finding.confidence:.0%}")
            if finding.tags:
                lines.append(f"**Tags**: {', '.join(f'`{t}`' for t in finding.tags)}")
            lines.append("")
            lines.append(finding.description)
            lines.append("")

            if finding.location.snippet:
                lines.append("```")
                lines.append(finding.location.snippet)
                lines.append("```")
                lines.append("")

            if finding.suggestion:
                lines.append(f"**Suggestion**: {finding.suggestion}")
                lines.append("")

            lines.append("---")
            lines.append("")

    # Footer
    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by CodeAudit v0.1.0 at {report.timestamp.strftime('%Y-%m-%d %H:%M UTC')}*")

    return "\n".join(lines)


def write_markdown_report(report: AuditReport, output_path: Path) -> None:
    """Write the markdown report to a file."""
    content = render_markdown_report(report)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
